### ISSUE TITLE
Problem with flash rendering that is fixed in 0.8; release 0.8?

### ISSUE THREAD

**Issue by cmawhorter** [paulhammond/webkit2png#88] opened 2015-06-03 22:31 UTC
For whatever reason, flash refuses to render with 0.7.  I found the `--debug` switch that displays the webview and confirmed it never renders.

0.8-dev has the debug switch documented and also fixes whatever problem 0.7 had that caused this behavior.

Release 0.8 to homebrew?

**Comment by paulhammond** [comment] 2020-03-26 02:38
This is weird, because at the time you wrote this bug the [only difference between 0.8-dev and 0.7](https://github.com/paulhammond/webkit2png/compare/v0.7...c0e91dea7c4fe9b39e2de994632a5123b518423b) was the version number string. Something else must have been different, and I'm curious what it was.

I'm going to close this bug assuming that you can no longer reproduce it but if you have any more details please reopen.

**Closed by paulhammond** 2020-03-26 02:38 UTC

**Comment by paulhammond** [comment] 2020-03-26 03:06
Oh, thinking about this more, it's probably that the `--debug` switch causes the window to be displayed, and webkit might be smart enough to not display plugins on hidden windows...
