### ISSUE TITLE
Rendering ripples if `width` is insufficient

### ISSUE THREAD

**Issue by scoates** [paulhammond/webkit2png#48] opened 2013-08-14 17:53 UTC
In v0.5 of webkit2png, rendering http://fictivekin.com/ was fine. As of 0.6 (and current HEAD), the resulting default image is rippled, and the small text is poorly-rendered.

HEAD on left, 0.5 on right (you'll need to zoom/show this full sized to see it, probably):
![ripples](https://f.cloud.github.com/assets/71983/963842/5a9e8164-050a-11e3-96dd-68f890db85ae.png)

However, if I specify `-W 1024` when capturing, I get the unrippled version.
If I specify `-W 800` (same as the default), I get the rippled image.

I took a quick dive into the options calculations, and it doesn't seem to be a floating point error, or similar. I don't grok the internals, though.

**Comment by paulhammond** [comment] 2020-03-26 01:12
I can't reproduce this so closing out.

**Closed by paulhammond** 2020-03-26 01:12 UTC
